// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v4.24.2
// source: tim.proto

package timtest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TidPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node     *string `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Domain   *string `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
	Resource *string `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Termtyp  *int32  `protobuf:"varint,4,opt,name=termtyp" json:"termtyp,omitempty"`
}

func (x *TidPb) Reset() {
	*x = TidPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidPb) ProtoMessage() {}

func (x *TidPb) ProtoReflect() protoreflect.Message {
	mi := &file_tim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidPb.ProtoReflect.Descriptor instead.
func (*TidPb) Descriptor() ([]byte, []int) {
	return file_tim_proto_rawDescGZIP(), []int{0}
}

func (x *TidPb) GetNode() string {
	if x != nil && x.Node != nil {
		return *x.Node
	}
	return ""
}

func (x *TidPb) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *TidPb) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *TidPb) GetTermtyp() int32 {
	if x != nil && x.Termtyp != nil {
		return *x.Termtyp
	}
	return 0
}

type TimPbMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsType    *int32            `protobuf:"varint,1,req,name=msType" json:"msType,omitempty"`
	OdType    *int32            `protobuf:"varint,2,req,name=odType" json:"odType,omitempty"`
	Id        *int64            `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Mid       *int64            `protobuf:"varint,4,opt,name=mid" json:"mid,omitempty"`
	BnType    *int32            `protobuf:"varint,5,opt,name=bnType" json:"bnType,omitempty"`
	FromTid   *TidPb            `protobuf:"bytes,6,opt,name=fromTid" json:"fromTid,omitempty"`
	ToTid     *TidPb            `protobuf:"bytes,7,opt,name=toTid" json:"toTid,omitempty"`
	Body      []byte            `protobuf:"bytes,8,opt,name=body" json:"body,omitempty"`
	IsOffline *bool             `protobuf:"varint,9,opt,name=isOffline" json:"isOffline,omitempty"`
	Timestamp *int64            `protobuf:"varint,10,opt,name=timestamp" json:"timestamp,omitempty"`
	Extend    map[string]string `protobuf:"bytes,11,rep,name=extend" json:"extend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *TimPbMessage) Reset() {
	*x = TimPbMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimPbMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimPbMessage) ProtoMessage() {}

func (x *TimPbMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimPbMessage.ProtoReflect.Descriptor instead.
func (*TimPbMessage) Descriptor() ([]byte, []int) {
	return file_tim_proto_rawDescGZIP(), []int{1}
}

func (x *TimPbMessage) GetMsType() int32 {
	if x != nil && x.MsType != nil {
		return *x.MsType
	}
	return 0
}

func (x *TimPbMessage) GetOdType() int32 {
	if x != nil && x.OdType != nil {
		return *x.OdType
	}
	return 0
}

func (x *TimPbMessage) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TimPbMessage) GetMid() int64 {
	if x != nil && x.Mid != nil {
		return *x.Mid
	}
	return 0
}

func (x *TimPbMessage) GetBnType() int32 {
	if x != nil && x.BnType != nil {
		return *x.BnType
	}
	return 0
}

func (x *TimPbMessage) GetFromTid() *TidPb {
	if x != nil {
		return x.FromTid
	}
	return nil
}

func (x *TimPbMessage) GetToTid() *TidPb {
	if x != nil {
		return x.ToTid
	}
	return nil
}

func (x *TimPbMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TimPbMessage) GetIsOffline() bool {
	if x != nil && x.IsOffline != nil {
		return *x.IsOffline
	}
	return false
}

func (x *TimPbMessage) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *TimPbMessage) GetExtend() map[string]string {
	if x != nil {
		return x.Extend
	}
	return nil
}

var File_tim_proto protoreflect.FileDescriptor

var file_tim_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x75,
	0x62, 0x22, 0x69, 0x0a, 0x05, 0x54, 0x69, 0x64, 0x50, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x72, 0x6d, 0x74, 0x79, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x72, 0x6d, 0x74, 0x79, 0x70, 0x22, 0x85, 0x03, 0x0a,
	0x0c, 0x54, 0x69, 0x6d, 0x50, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x62, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x54,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e,
	0x54, 0x69, 0x64, 0x50, 0x62, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x05, 0x74, 0x6f, 0x54, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x73, 0x74, 0x75, 0x62, 0x2e, 0x54, 0x69, 0x64, 0x50, 0x62, 0x52, 0x05, 0x74, 0x6f, 0x54, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x36, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x18, 0x0b, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x50, 0x62, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x1a, 0x39, 0x0a, 0x0b, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62,
}

var (
	file_tim_proto_rawDescOnce sync.Once
	file_tim_proto_rawDescData = file_tim_proto_rawDesc
)

func file_tim_proto_rawDescGZIP() []byte {
	file_tim_proto_rawDescOnce.Do(func() {
		file_tim_proto_rawDescData = protoimpl.X.CompressGZIP(file_tim_proto_rawDescData)
	})
	return file_tim_proto_rawDescData
}

var file_tim_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tim_proto_goTypes = []interface{}{
	(*TidPb)(nil),        // 0: stub.TidPb
	(*TimPbMessage)(nil), // 1: stub.TimPbMessage
	nil,                  // 2: stub.TimPbMessage.ExtendEntry
}
var file_tim_proto_depIdxs = []int32{
	0, // 0: stub.TimPbMessage.fromTid:type_name -> stub.TidPb
	0, // 1: stub.TimPbMessage.toTid:type_name -> stub.TidPb
	2, // 2: stub.TimPbMessage.extend:type_name -> stub.TimPbMessage.ExtendEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tim_proto_init() }
func file_tim_proto_init() {
	if File_tim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimPbMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tim_proto_goTypes,
		DependencyIndexes: file_tim_proto_depIdxs,
		MessageInfos:      file_tim_proto_msgTypes,
	}.Build()
	File_tim_proto = out.File
	file_tim_proto_rawDesc = nil
	file_tim_proto_goTypes = nil
	file_tim_proto_depIdxs = nil
}
